---
apiVersion: v1
kind: Service
metadata:
  name: inventory-broker-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: inventory-broker-postgres
type: LoadBalancer

---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-broker-postgres
  labels:
    app: inventory-broker-postgres
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: inventory-broker-postgres
    tags.datadoghq.com/version: "1.0"
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 2
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgresql-db
        image: postgres:latest
        volumeMounts:
        - name: postgresql-db-disk
          mountPath: /data
        env:
        - name: POSTGRES_PASSWORD
          value: testpassword
        - name: PGDATA
          value: /data/pgdata
        - name: DD_LOGS_INJECTION
          value: "true"  
      # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Gi
